[package]
name = "todo_app"
version = "0.1.0"
authors = ["Kevin Brunner <kevin.rene.brunner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
todo_lib = {path="../todo_lib"}